name: build

env:
  PREFIX: RkHelper
  DOTNET_SDK_VERSION: '5.0.100'

on:
  workflow_call:
    inputs:
      build-configuration:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      build-configuration:
        description: "Build configuration for msbuild"
        required: true
        type: choice
        options:
          - Debug
          - Release

jobs:
  cli-build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    - name: Build
      run: dotnet build --configuration ${{ inputs.build-configuration }} ${{ env.PREFIX }}

    - name: Packaging
      run: dotnet pack --configuration ${{ inputs.build-configuration }} --no-build -o ./publish ${{ env.PREFIX }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PREFIX }}-${{ inputs.build-configuration }}
        path: ./publish/
