name: build

env:
  PREFIX: RkHelper
  DOTNET_SDK_VERSION: '5.0.100'

on:
  workflow_call:
    inputs:
      build-configuration:
        required: true
        type: string
      custom-version:
        required: false
        type: string
        default: "0.0.0"

  workflow_dispatch:
    inputs:
      build-configuration:
        description: "Build configuration for msbuild"
        required: true
        type: choice
        options:
          - Debug
          - Release
      custom-version:
        description: "Package Version (format: x.y.z)"
        required: false
        type: string
        default: "0.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    - name: Build
      run: dotnet build --configuration ${{ inputs.build-configuration }} -p:Version=${{ inputs.custom-version }} ${{ env.PREFIX }}

    - name: Packaging
      run: dotnet pack --configuration ${{ inputs.build-configuration }} --no-build -p:Version=${{ inputs.custom-version }} -o ./publish ${{ env.PREFIX }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PREFIX }}-${{ inputs.build-configuration }}
        path: ./publish/

    - name: Github Actions Summary
      run: |
        echo "|---|---|" >> $GITHUB_STEP_SUMMARY
        echo "|Name|Value|" >> $GITHUB_STEP_SUMMARY
        echo "|Branch|`${{ github.ref_name }}`|" >> $GITHUB_STEP_SUMMARY
        echo "|Commit-SHA|`${{ github.sha }}`|" >> $GITHUB_STEP_SUMMARY
        echo "|Version|`${{ inputs.custom-version }}`|" >> $GITHUB_STEP_SUMMARY
        echo "|Build Configuration|`${{ inputs.build-configuration }}`|" >> $GITHUB_STEP_SUMMARY
