name: nuget_deploy
on:
  push:
    tags:
      - ver-*.*.*
      - ver-[0-9]+

env:
  PREFIX: RkHelper
  DOTNET_SDK_VERSION: '5.0.100'

jobs:
  nuget_deploy:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    - name: Parse Tag
      run: |
        echo "VER_TAG=${GITHUB_REF#refs/tags/ver-}" >> $GITHUB_ENV
        echo Version is ${{ env.VER_TAG }}

    - name: Build
      run: dotnet build --configuration Release -p:Version=${{ env.VER_TAG }} ${{ env.PREFIX }}

    - name: Packaging
      run: dotnet pack --configuration Release --no-build -p:Version=${{ env.VER_TAG }} -o ./publish ${{ env.PREFIX }}

    - name: Upload artifact file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PREFIX }}-${{ env.VER_TAG }}
        path: ./publish/

    - name: Uploading to NuGet
      run: dotnet nuget push publish/*.nupkg -k $NUGET_API_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_TOKEN: ${{ secrets.NUGET_API_TOKEN }}
